import { jsPDF } from "jspdf";

export function generateTransactionReceipt(transaction) {
  const doc = new jsPDF();

  let y = 20;

  doc.setFontSize(20);
  doc.text("LedgerCore", 20, y);

  y += 10;

  doc.setFontSize(14);
  doc.text("Transaction Receipt", 20, y);

  y += 15;

  doc.setFontSize(11);

  doc.text(`Transaction ID: ${transaction._id}`, 20, y);
  y += 10;

  doc.text(`Amount: ₹${transaction.amount}`, 20, y);
  y += 10;

  doc.text(`Status: ${transaction.status}`, 20, y);
  y += 10;

  doc.text(`Direction: ${transaction.direction}`, 20, y);
  y += 10;

  doc.text(`Type: ${transaction.transactionType}`, 20, y);
  y += 10;

  doc.text(`Category: ${transaction.category}`, 20, y);
  y += 15;

  doc.text("From Account", 20, y);
  y += 8;
  doc.text(transaction.fromAccount.name, 30, y);

  y += 15;

  doc.text("To Account", 20, y);
  y += 8;
  doc.text(transaction.toAccount.name, 30, y);

  y += 20;

  doc.setFontSize(13);
  doc.text("Ledger Entries", 20, y);

  y += 10;

  transaction.ledgerEntries.forEach((entry) => {
    doc.setFontSize(11);

    doc.text(
      `${entry.type} | ${entry.account.name} | ₹${entry.amount}`,
      25,
      y
    );

    y += 10;
  });

  y += 10;

  doc.setFontSize(10);

  doc.text(
    `Generated on: ${new Date().toLocaleString()}`,
    20,
    y
  );

  y += 8;

  doc.text("Generated by LedgerCore", 20, y);

  doc.save(`LedgerCore_Transaction_${transaction._id}.pdf`);
}